name: Weekly generate Java 8, 11, and 16 tool cache
on:
  schedule:
    - cron: '21 1 * * 1'
  workflow_dispatch:

jobs:
  upload_go_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf java_tool_cache.tar.gz *

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/java_tool_cache.tar.gz
