name: Weekly generate Go 1.15, 1.16 and 1.17 tool cache
on:
  schedule:
    - cron: '26 1 * * 1'
  workflow_dispatch:

jobs:
  upload_go_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"

      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf go_tool_cache.tar.gz *

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/go_tool_cache.tar.gz
