name: Weekly generate Python 3.7, 3.8, 3.9 and 3.10 tool cache
on:
  schedule:
    - cron: '17 1 * * 1'
  workflow_dispatch:

jobs:
  upload_node_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf python_tool_cache.tar.gz *

      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/python_tool_cache.tar.gz
